name: rssgrab
dependencies:
- bcrypt=2.0.0=py35_0
- beautifulsoup4=4.4.1=py35_0
- cffi=1.6.0=py35_0
- feedparser=5.2.1=py35_0
- flask=0.10.1=py35_1
- itsdangerous=0.24=py35_0
- jinja2=2.8=py35_0
- markupsafe=0.23=py35_0
- openssl=1.0.2f=0
- pip=8.0.2=py35_0
- pycparser=2.14=py35_1
- pymongo=3.0.3=py35_0
- python=3.5.1=0
- pyyaml=3.11=py35_1
- readline=6.2=2
- requests=2.9.1=py35_0
- setuptools=19.6.2=py35_0
- six=1.10.0=py35_0
- sqlite=3.9.2=0
- tk=8.5.18=0
- werkzeug=0.11.3=py35_0
- wheel=0.26.0=py35_1
- xz=5.0.5=0
- yaml=0.1.6=0
- zlib=1.2.8=0
- pip:
  - apscheduler==3.0.5
  - behave==1.2.5
  - flask-cors==2.1.2
  - parse==1.6.6
  - parse-type==0.3.4
  - pyjwt==1.4.0
  - pytz==2015.7
  - tzlocal==1.2

